name: test config file yaml

on: 
    workflow_dispatch:
        inputs:
            customer:
              description: "name of customer"
              required: true
              type: choice
              options:
                  - lululemon
                  - menards

jobs:
    production-deploy:
          name: lulu-build
          if: inputs.customer == 'lululemon'
          runs-on: ubuntu-latest
          steps:
            - name: print the word
              run: |
                echo ${{ inputs.customer}}
          
    reload-deploy:
          name: menards-build
          if: inputs.customer == 'menards'
          runs-on: ubuntu-latest
          steps:
            - name: print the word
              run: |
                echo ${{ inputs.customer }}