name: test config file yaml

on: push
    # workflow_dispatch:
    #     inputs:
    #         cluster_name:
    #           description: "name of customer"
    #           required: true
    #           type: choice
    #           options:
    #             - devopslab.cloud
    #             - documentation.io
    #         kops_state_store:
    #           description: "where the state will be stored"
    #           required: true
    #           type: choice
    #           options:
    #             - kops-state-bk
    #             - tfst-bk
    #         zones:
    #           description: "zone to create"
    #           required: true
    #           type: choice
    #           options:
    #             - "us-east-1a,us-east-1b,us-east-1c"
    #             - "us-east-2a,us-east-2b,us-east-2c"
    #         node_count:
    #           description: "node count"
    #           required: true
    #           type: choice
    #           options:
    #             - 2
    #             - 3
    #             - 4
    #         node_size:
    #           description: "node size"
    #           required: true
    #           type: choice
    #           options:
    #             - t2.micro
    #             - t3.medium
    #         master_node_size:
    #           description: "master node size"
    #           required: true
    #           type: choice
    #           options:
    #             - t2.micro
    #             - t3.medium

env:
  cluster_name: ${{ inputs.cluster_name }}
  kops_state_store: ${{ inputs.kops_state_store }}
  zone: ${{ inputs.zone}}
  node_count: ${{ inputs.node_count }}
  node_size: ${{ inputs.node_size }}
  master_node_size: ${{ inputs.master_node_size }}

jobs:
  cluster_creation:
      name: "cluster creation"
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: setting up kops
          run: | 
              curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
              chmod +x kops
              sudo mv kops /usr/local/bin/kops
        
        # - name: delete cluster
        #   run: |
        #        export KOPS_STATE_STORE="s3://kops-state-bk"
        #        kops delete cluster devopslab.cloud --yes
        - name: creating the cluster
          run: |
              export KOPS_STATE_STORE=s3://kops-state-bk2
              export NAME=kubeclusterapp.com
              export CONTROL_PLANE_SIZE="c5.large"
              export NODE_SIZE="m5.large"
              export ZONES="us-east-1a,us-east-1b,us-east-1c"
              kops create cluster $NAME \
              --node-count 3 \
              --zones $ZONES \
              --node-size $NODE_SIZE \
              --control-plane-size $CONTROL_PLANE_SIZE \
              --control-plane-zones $ZONES \
              --networking cilium \
              --topology private \
              --bastion="true" \
              --yes 

              
            